test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

default: &default
  adapter: postgresql
  port: 5432
  database: statisticdb
  username: statistic
  password: <%= ENV['STATISTIC_DB_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost

statistic_development:
  <<: *default
  host: localhost

production:
  <<: *default
  host: statistic-db.local

statistic_production:
  <<: *default
  host: statistic-db.local
